### ISSUE TITLE
[Bug]: Tales of Rebirth SkitViewer

### ISSUE THREAD

**Issue by Fis-Ura** [SymphoniaLauren/Tales-of-Rebirth#106]
### Version details

No Patch released yet

### Contact Details

Pegi

### What happened?

The skit npc has a problem with list menus, it seems to have one too many new line which breaks the menu inputs. This is even the case with a blank japanese file.

**Comment by Fis-Ura** [comment]
![image](https://github.com/SymphoniaLauren/Tales-of-Rebirth/assets/77898683/c022fe39-54e9-4eb4-8474-477a1718cc4b)

@Mc-muffin This is still and issue, it only works with the modified psp file Lauren is using.

**Comment by Mc-muffin** [comment]
I thought this was mistakenly closed for a second

**Comment by Fis-Ura** [comment]
Finally fixed
