### ISSUE TITLE
[Bug]: Tales of Rebirth Mouth/Lip Data

### ISSUE THREAD

**Issue by JulianoW** [SymphoniaLauren/Tales-of-Rebirth#348]
### Version details

n/a

### Contact Details

Julian

### What happened?

Lip data for some skits is borked, see: Hilda tarot reading. 14781 in pak2.

Per Lauren, 0x4 in the header should be zero, or something? I don't know.

**Comment by Mc-muffin** [comment]
This should've been fixed since lifebottle/pythonlib@e54c0c2a967ce92d8514a91d3aeedf77a409cbfe, has it been tested?

**Comment by Fis-Ura** [comment]
> This should've been fixed since [lifebottle/PythonLib@e54c0c2](https://github.com/lifebottle/PythonLib/commit/e54c0c2a967ce92d8514a91d3aeedf77a409cbfe), has it been tested?

This has not fixed the issue, it is still broken with the latest python lib

**Comment by Mc-muffin** [comment]
Fixed upstream

**Comment by Fis-Ura** [comment]
Works when rebuild all is done with the bat file, since it need to rebuild pak2
