### ISSUE TITLE
[Improvement]: Tales of Rebirth Escaped String need to be split

### ISSUE THREAD

**Issue by Fis-Ura** [SymphoniaLauren/Tales-of-Rebirth#389]
### Version details

No Patch released yet

### Contact Details

Pegi

### What happened?

![image](https://github.com/user-attachments/assets/c2179883-c766-48eb-91b3-0a4dc0676a0d)

This string is used at two places in the battle overlay, it would need to be split and one of them need to yeeted

**Comment by Mc-muffin** [comment]
These are now split
