### ISSUE TITLE
[Improvement]: Tales of Rebirth Number Spacing and % Sign

### ISSUE THREAD

**Issue by Fis-Ura** [SymphoniaLauren/Tales-of-Rebirth#63]
### Version details

N/A

### Contact Details

Pegi

### What happened?

![image](https://github.com/SymphoniaLauren/Tales-of-Rebirth/assets/77898683/2980c8ca-823c-4134-8369-abf577158003)
I believe we might be using the japanese number for this since not using them crash the game. See Triangle menu numbers. If so maybe we could take a look at the spacing if we can adjust the monospace number to be closer togheter.

![image](https://github.com/SymphoniaLauren/Tales-of-Rebirth/assets/77898683/ea6ac169-3697-4f56-8e44-b7c37bae7beb)

**Comment by JulianoW** [comment]
fix for this is ready, hopefully tomorrow

**Comment by Fis-Ura** [comment]
This seems to be a font spacing issue for the letter spacing since after the fix we still have spaced letter @SymphoniaLauren 

we could also fix the % sign 

![image](https://github.com/user-attachments/assets/fcf6ab15-eed5-4740-820d-6d8e47ec574d)

**Comment by Fis-Ura** [comment]
i'ne done the best i could now it's up to lauren

**Comment by Fis-Ura** [comment]
Done
